Repository traefik/mkdocs-material, pull requests merged in 2021-01, with the labels that each got.

#3 Fix 1st publishing
  README.md
  package-lock.json
  package.json
Labels: status/3-needs-merge

#5 Fix dropdown menu icon rotation to stay centered
  material/assets/stylesheets/main.css
  material/partials/nav-item.html
  package-lock.json
  src/assets/stylesheets/main/layout/_nav.scss
  src/partials/nav-item.html
Labels: kind/bug/fix, status/3-needs-merge

#7 Fix menu links
  src/partials/company-header.html
Labels: kind/bug/fix, status/3-needs-merge

#9 Keep js outside theme
  material/assets/stylesheets/main.css
  material/base.html
  material/partials/language/es.html
  mkdocs.yml
  src/assets/javascripts/utilities/hljs/LICENSE
  src/assets/javascripts/utilities/hljs/extra.js
  src/assets/javascripts/utilities/hljs/highlight.pack.js
  src/base.html
Labels: kind/bug/fix, status/3-needs-merge

#14 Fix narrow tables shadow
  src/assets/stylesheets/main/_typeset.scss
Labels: kind/bug/fix, status/3-needs-merge

#18 Disable doc build/deploy on main and keep it only on master
  .github/workflows/documentation.yml
Labels: status/3-needs-merge

#16 Fix side menus overriding footer or hidden by the footer
  material/assets/stylesheets/main.9f219632.min.css
  material/assets/stylesheets/main.9f219632.min.css.map
  src/assets/stylesheets/main/layout/_sidebar.scss
Labels: kind/bug/fix, status/3-needs-merge

#12 release theme in v100.0.1
  package-lock.json
  package.json
Labels: status/3-needs-merge

#19 clean material folder
  material/assets/stylesheets/main.9f219632.min.css
  material/assets/stylesheets/main.9f219632.min.css.map
Labels: status/3-needs-merge

#20 Prepare release 100.0.2
  package.json
Labels: status/3-needs-merge

#21 prepare release 100.0.3
  package-lock.json
  package.json
Labels: status/3-needs-merge

#27 Handle marie feedbacks
  material/assets/manifest.json
  material/assets/stylesheets/main.3922e514.min.css
  material/assets/stylesheets/main.3922e514.min.css.map
  material/assets/stylesheets/main.dabd0485.min.css
  material/assets/stylesheets/main.dabd0485.min.css.map
  material/base.html
  material/partials/company-header.html
  material/partials/product-switcher.html
  src/assets/stylesheets/customizations/_header.scss
  src/assets/stylesheets/customizations/_product-switcher.scss
  src/assets/stylesheets/customizations/_root.scss
  src/assets/stylesheets/main/layout/_sidebar.scss
  src/partials/company-header.html
  src/partials/product-switcher.html
Labels: kind/bug/fix, status/3-needs-merge

#28 Rm mesh from solutions in menu
  material/partials/company-header.html
  src/partials/company-header.html
Labels: status/3-needs-merge

#29 Prepare release 100.0.5
  material/base.html
  package-lock.json
  package.json
Labels: status/3-needs-merge

#30 Handle marie feedbacks 2
  material/assets/images/Kubernetes-and-Helm-blog-2.jpg
  material/assets/images/Kubernetes-for-Cloud-Native-Application-Networks.jpg
  material/assets/images/Traefik-Enterprise-Demo-Video.jpg
  material/assets/images/TraefikEnterprise-SpecialWebinar.jpg
  material/assets/images/Vaudoise-Case-Study-Traefik-Enterprise.png
  material/assets/manifest.json
  material/assets/stylesheets/main.00bc1f03.min.css
  material/assets/stylesheets/main.00bc1f03.min.css.map
  material/assets/stylesheets/main.dabd0485.min.css
  material/assets/stylesheets/main.dabd0485.min.css.map
  material/base.html
  material/partials/company-header.html
  material/partials/product-switcher.html
  mkdocs.yml
  src/assets/images/Kubernetes-and-Helm-blog-2.jpg
  src/assets/images/Kubernetes-for-Cloud-Native-Application-Networks.jpg
  src/assets/images/Traefik-Enterprise-Demo-Video.jpg
  src/assets/images/TraefikEnterprise-SpecialWebinar.jpg
  src/assets/images/Vaudoise-Case-Study-Traefik-Enterprise.png
  src/assets/stylesheets/customizations/_header.scss
  src/assets/stylesheets/customizations/_menu.scss
  src/assets/stylesheets/customizations/_product-switcher.scss
  src/assets/stylesheets/customizations/_root.scss
  src/assets/stylesheets/main/layout/_base.scss
  src/assets/stylesheets/main/layout/_nav.scss
  src/assets/stylesheets/main/layout/_search.scss
  src/assets/stylesheets/main/layout/_sidebar.scss
  src/partials/company-header.html
  src/partials/product-switcher.html
Labels: kind/bug/fix, status/3-needs-merge

#31 Prepare release 100.0.6
  material/base.html
  package-lock.json
  package.json
Labels: status/3-needs-merge

#32 Fix menu images not displayed when using jpg
  material/assets/images/Kubernetes-and-Helm-blog-2.jpg
  material/assets/images/Kubernetes-and-Helm-blog-2.png
  material/assets/images/Kubernetes-for-Cloud-Native-Application-Networks.jpg
  material/assets/images/Kubernetes-for-Cloud-Native-Application-Networks.png
  material/assets/images/Traefik-Enterprise-Demo-Video.jpg
  material/assets/images/Traefik-Enterprise-Demo-Video.png
  material/assets/images/TraefikEnterprise-SpecialWebinar.jpg
  material/assets/images/TraefikEnterprise-SpecialWebinar.png
  material/partials/company-header.html
  src/assets/images/Kubernetes-and-Helm-blog-2.jpg
  src/assets/images/Kubernetes-and-Helm-blog-2.png
  src/assets/images/Kubernetes-for-Cloud-Native-Application-Networks.jpg
  src/assets/images/Kubernetes-for-Cloud-Native-Application-Networks.png
  src/assets/images/Traefik-Enterprise-Demo-Video.jpg
  src/assets/images/Traefik-Enterprise-Demo-Video.png
  src/assets/images/TraefikEnterprise-SpecialWebinar.jpg
  src/assets/images/TraefikEnterprise-SpecialWebinar.png
  src/partials/company-header.html
Labels: kind/bug/fix, status/3-needs-merge

#33 Prepare release 100.0.7
  material/base.html
  package-lock.json
  package.json
  setup.py
Labels: status/3-needs-merge

#42 Prepare release 100.0.8
  material/base.html
  package-lock.json
  package.json
Labels: kind/enhancement, status/3-needs-merge

#40 Fix sidebars not scrollable
  material/assets/manifest.json
  material/assets/stylesheets/main.71dff81d.min.css
  material/assets/stylesheets/main.71dff81d.min.css.map
  material/assets/stylesheets/main.e7836616.min.css
  material/assets/stylesheets/main.e7836616.min.css.map
  material/base.html
  material/partials/company-header.html
  material/partials/header.html
  src/assets/stylesheets/customizations/_menu.scss
  src/assets/stylesheets/main/layout/_nav.scss
  src/assets/stylesheets/main/layout/_search.scss
  src/assets/stylesheets/main/layout/_sidebar.scss
  src/base.html
  src/partials/company-header.html
  src/partials/header.html
Labels: kind/bug/fix, status/3-needs-merge

#44 Add favicon for each product and make them switch color according to the OS Theme
  material/assets/images/favicon.ico
  material/assets/images/logo-traefik-enterprise-icon.svg
  material/assets/images/logo-traefik-mesh-icon.svg
  material/assets/images/logo-traefik-pilot-icon.svg
  material/assets/images/logo-traefik-proxy-icon.svg
  material/base.html
  mkdocs.yml
  src/assets/images/favicon.ico
  src/assets/images/logo-traefik-enterprise-icon.svg
  src/assets/images/logo-traefik-mesh-icon.svg
  src/assets/images/logo-traefik-pilot-icon.svg
  src/assets/images/logo-traefik-proxy-icon.svg
  src/base.html
Labels: kind/bug/fix, status/3-needs-merge
